/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iotdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IotDslUiModule extends AbstractIotDslUiModule {

	public IotDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
