/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iotdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.iotdsl.ui.internal.IotdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IotDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IotdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IotdslActivator activator = IotdslActivator.getInstance();
		return activator != null ? activator.getInjector(IotdslActivator.ORG_XTEXT_EXAMPLE_IOTDSL_IOTDSL) : null;
	}

}
