/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iotdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IotDslStandaloneSetup extends IotDslStandaloneSetupGenerated {

	public static void doSetup() {
		new IotDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
