/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iotdsl.iotDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Estado</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.Estado#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.Estado#getAcoes <em>Acoes</em>}</li>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.Estado#getTransacoes <em>Transacoes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getEstado()
 * @model
 * @generated
 */
public interface Estado extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getEstado_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.iotdsl.iotDsl.Estado#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Acoes</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.iotdsl.iotDsl.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Acoes</em>' reference list.
   * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getEstado_Acoes()
   * @model
   * @generated
   */
  EList<Comando> getAcoes();

  /**
   * Returns the value of the '<em><b>Transacoes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.iotdsl.iotDsl.Transacao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transacoes</em>' containment reference list.
   * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getEstado_Transacoes()
   * @model containment="true"
   * @generated
   */
  EList<Transacao> getTransacoes();

} // Estado
