/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iotdsl.iotDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.iotdsl.iotDsl.IotDslFactory
 * @model kind="package"
 * @generated
 */
public interface IotDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "iotDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/iotdsl/IotDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "iotDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IotDslPackage eINSTANCE = org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.iotdsl.iotDsl.impl.IotDslImpl <em>Iot Dsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslImpl
   * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getIotDsl()
   * @generated
   */
  int IOT_DSL = 0;

  /**
   * The feature id for the '<em><b>Eventos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_DSL__EVENTOS = 0;

  /**
   * The feature id for the '<em><b>Reset Eventos</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_DSL__RESET_EVENTOS = 1;

  /**
   * The feature id for the '<em><b>Comandos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_DSL__COMANDOS = 2;

  /**
   * The feature id for the '<em><b>Estados</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_DSL__ESTADOS = 3;

  /**
   * The number of structural features of the '<em>Iot Dsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IOT_DSL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.iotdsl.iotDsl.impl.EventoImpl <em>Evento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iotdsl.iotDsl.impl.EventoImpl
   * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getEvento()
   * @generated
   */
  int EVENTO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENTO__NAME = 0;

  /**
   * The number of structural features of the '<em>Evento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENTO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.iotdsl.iotDsl.impl.ComandoImpl <em>Comando</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iotdsl.iotDsl.impl.ComandoImpl
   * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getComando()
   * @generated
   */
  int COMANDO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO__NAME = 0;

  /**
   * The number of structural features of the '<em>Comando</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.iotdsl.iotDsl.impl.EstadoImpl <em>Estado</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iotdsl.iotDsl.impl.EstadoImpl
   * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getEstado()
   * @generated
   */
  int ESTADO = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTADO__NAME = 0;

  /**
   * The feature id for the '<em><b>Acoes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTADO__ACOES = 1;

  /**
   * The feature id for the '<em><b>Transacoes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTADO__TRANSACOES = 2;

  /**
   * The number of structural features of the '<em>Estado</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTADO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.iotdsl.iotDsl.impl.TransacaoImpl <em>Transacao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.iotdsl.iotDsl.impl.TransacaoImpl
   * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getTransacao()
   * @generated
   */
  int TRANSACAO = 4;

  /**
   * The feature id for the '<em><b>Evento</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACAO__EVENTO = 0;

  /**
   * The feature id for the '<em><b>Estado</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACAO__ESTADO = 1;

  /**
   * The number of structural features of the '<em>Transacao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACAO_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.iotdsl.iotDsl.IotDsl <em>Iot Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Iot Dsl</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.IotDsl
   * @generated
   */
  EClass getIotDsl();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.iotdsl.iotDsl.IotDsl#getEventos <em>Eventos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Eventos</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.IotDsl#getEventos()
   * @see #getIotDsl()
   * @generated
   */
  EReference getIotDsl_Eventos();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.iotdsl.iotDsl.IotDsl#getResetEventos <em>Reset Eventos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Reset Eventos</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.IotDsl#getResetEventos()
   * @see #getIotDsl()
   * @generated
   */
  EReference getIotDsl_ResetEventos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.iotdsl.iotDsl.IotDsl#getComandos <em>Comandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comandos</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.IotDsl#getComandos()
   * @see #getIotDsl()
   * @generated
   */
  EReference getIotDsl_Comandos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.iotdsl.iotDsl.IotDsl#getEstados <em>Estados</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Estados</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.IotDsl#getEstados()
   * @see #getIotDsl()
   * @generated
   */
  EReference getIotDsl_Estados();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iotdsl.iotDsl.Evento <em>Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evento</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Evento
   * @generated
   */
  EClass getEvento();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iotdsl.iotDsl.Evento#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Evento#getName()
   * @see #getEvento()
   * @generated
   */
  EAttribute getEvento_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iotdsl.iotDsl.Comando <em>Comando</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Comando
   * @generated
   */
  EClass getComando();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iotdsl.iotDsl.Comando#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Comando#getName()
   * @see #getComando()
   * @generated
   */
  EAttribute getComando_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iotdsl.iotDsl.Estado <em>Estado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Estado</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Estado
   * @generated
   */
  EClass getEstado();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.iotdsl.iotDsl.Estado#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Estado#getName()
   * @see #getEstado()
   * @generated
   */
  EAttribute getEstado_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.iotdsl.iotDsl.Estado#getAcoes <em>Acoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Acoes</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Estado#getAcoes()
   * @see #getEstado()
   * @generated
   */
  EReference getEstado_Acoes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.iotdsl.iotDsl.Estado#getTransacoes <em>Transacoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transacoes</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Estado#getTransacoes()
   * @see #getEstado()
   * @generated
   */
  EReference getEstado_Transacoes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.iotdsl.iotDsl.Transacao <em>Transacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transacao</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Transacao
   * @generated
   */
  EClass getTransacao();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.iotdsl.iotDsl.Transacao#getEvento <em>Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Evento</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Transacao#getEvento()
   * @see #getTransacao()
   * @generated
   */
  EReference getTransacao_Evento();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.iotdsl.iotDsl.Transacao#getEstado <em>Estado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Estado</em>'.
   * @see org.xtext.example.iotdsl.iotDsl.Transacao#getEstado()
   * @see #getTransacao()
   * @generated
   */
  EReference getTransacao_Estado();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IotDslFactory getIotDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.iotdsl.iotDsl.impl.IotDslImpl <em>Iot Dsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslImpl
     * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getIotDsl()
     * @generated
     */
    EClass IOT_DSL = eINSTANCE.getIotDsl();

    /**
     * The meta object literal for the '<em><b>Eventos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IOT_DSL__EVENTOS = eINSTANCE.getIotDsl_Eventos();

    /**
     * The meta object literal for the '<em><b>Reset Eventos</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IOT_DSL__RESET_EVENTOS = eINSTANCE.getIotDsl_ResetEventos();

    /**
     * The meta object literal for the '<em><b>Comandos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IOT_DSL__COMANDOS = eINSTANCE.getIotDsl_Comandos();

    /**
     * The meta object literal for the '<em><b>Estados</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IOT_DSL__ESTADOS = eINSTANCE.getIotDsl_Estados();

    /**
     * The meta object literal for the '{@link org.xtext.example.iotdsl.iotDsl.impl.EventoImpl <em>Evento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iotdsl.iotDsl.impl.EventoImpl
     * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getEvento()
     * @generated
     */
    EClass EVENTO = eINSTANCE.getEvento();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENTO__NAME = eINSTANCE.getEvento_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.iotdsl.iotDsl.impl.ComandoImpl <em>Comando</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iotdsl.iotDsl.impl.ComandoImpl
     * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getComando()
     * @generated
     */
    EClass COMANDO = eINSTANCE.getComando();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMANDO__NAME = eINSTANCE.getComando_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.iotdsl.iotDsl.impl.EstadoImpl <em>Estado</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iotdsl.iotDsl.impl.EstadoImpl
     * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getEstado()
     * @generated
     */
    EClass ESTADO = eINSTANCE.getEstado();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESTADO__NAME = eINSTANCE.getEstado_Name();

    /**
     * The meta object literal for the '<em><b>Acoes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESTADO__ACOES = eINSTANCE.getEstado_Acoes();

    /**
     * The meta object literal for the '<em><b>Transacoes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESTADO__TRANSACOES = eINSTANCE.getEstado_Transacoes();

    /**
     * The meta object literal for the '{@link org.xtext.example.iotdsl.iotDsl.impl.TransacaoImpl <em>Transacao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.iotdsl.iotDsl.impl.TransacaoImpl
     * @see org.xtext.example.iotdsl.iotDsl.impl.IotDslPackageImpl#getTransacao()
     * @generated
     */
    EClass TRANSACAO = eINSTANCE.getTransacao();

    /**
     * The meta object literal for the '<em><b>Evento</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSACAO__EVENTO = eINSTANCE.getTransacao_Evento();

    /**
     * The meta object literal for the '<em><b>Estado</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSACAO__ESTADO = eINSTANCE.getTransacao_Estado();

  }

} //IotDslPackage
