/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iotdsl.iotDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Iot Dsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.IotDsl#getEventos <em>Eventos</em>}</li>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.IotDsl#getResetEventos <em>Reset Eventos</em>}</li>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.IotDsl#getComandos <em>Comandos</em>}</li>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.IotDsl#getEstados <em>Estados</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getIotDsl()
 * @model
 * @generated
 */
public interface IotDsl extends EObject
{
  /**
   * Returns the value of the '<em><b>Eventos</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.iotdsl.iotDsl.Evento}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eventos</em>' containment reference list.
   * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getIotDsl_Eventos()
   * @model containment="true"
   * @generated
   */
  EList<Evento> getEventos();

  /**
   * Returns the value of the '<em><b>Reset Eventos</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.iotdsl.iotDsl.Evento}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reset Eventos</em>' reference list.
   * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getIotDsl_ResetEventos()
   * @model
   * @generated
   */
  EList<Evento> getResetEventos();

  /**
   * Returns the value of the '<em><b>Comandos</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.iotdsl.iotDsl.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos</em>' containment reference list.
   * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getIotDsl_Comandos()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComandos();

  /**
   * Returns the value of the '<em><b>Estados</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.iotdsl.iotDsl.Estado}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Estados</em>' containment reference list.
   * @see org.xtext.example.iotdsl.iotDsl.IotDslPackage#getIotDsl_Estados()
   * @model containment="true"
   * @generated
   */
  EList<Estado> getEstados();

} // IotDsl
