/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iotdsl.iotDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.iotdsl.iotDsl.Comando;
import org.xtext.example.iotdsl.iotDsl.Estado;
import org.xtext.example.iotdsl.iotDsl.IotDslPackage;
import org.xtext.example.iotdsl.iotDsl.Transacao;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Estado</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.impl.EstadoImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.impl.EstadoImpl#getAcoes <em>Acoes</em>}</li>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.impl.EstadoImpl#getTransacoes <em>Transacoes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EstadoImpl extends MinimalEObjectImpl.Container implements Estado
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAcoes() <em>Acoes</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAcoes()
   * @generated
   * @ordered
   */
  protected EList<Comando> acoes;

  /**
   * The cached value of the '{@link #getTransacoes() <em>Transacoes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransacoes()
   * @generated
   * @ordered
   */
  protected EList<Transacao> transacoes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EstadoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IotDslPackage.Literals.ESTADO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotDslPackage.ESTADO__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comando> getAcoes()
  {
    if (acoes == null)
    {
      acoes = new EObjectResolvingEList<Comando>(Comando.class, this, IotDslPackage.ESTADO__ACOES);
    }
    return acoes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Transacao> getTransacoes()
  {
    if (transacoes == null)
    {
      transacoes = new EObjectContainmentEList<Transacao>(Transacao.class, this, IotDslPackage.ESTADO__TRANSACOES);
    }
    return transacoes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IotDslPackage.ESTADO__TRANSACOES:
        return ((InternalEList<?>)getTransacoes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IotDslPackage.ESTADO__NAME:
        return getName();
      case IotDslPackage.ESTADO__ACOES:
        return getAcoes();
      case IotDslPackage.ESTADO__TRANSACOES:
        return getTransacoes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IotDslPackage.ESTADO__NAME:
        setName((String)newValue);
        return;
      case IotDslPackage.ESTADO__ACOES:
        getAcoes().clear();
        getAcoes().addAll((Collection<? extends Comando>)newValue);
        return;
      case IotDslPackage.ESTADO__TRANSACOES:
        getTransacoes().clear();
        getTransacoes().addAll((Collection<? extends Transacao>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IotDslPackage.ESTADO__NAME:
        setName(NAME_EDEFAULT);
        return;
      case IotDslPackage.ESTADO__ACOES:
        getAcoes().clear();
        return;
      case IotDslPackage.ESTADO__TRANSACOES:
        getTransacoes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IotDslPackage.ESTADO__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case IotDslPackage.ESTADO__ACOES:
        return acoes != null && !acoes.isEmpty();
      case IotDslPackage.ESTADO__TRANSACOES:
        return transacoes != null && !transacoes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EstadoImpl
