/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iotdsl.iotDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.iotdsl.iotDsl.Estado;
import org.xtext.example.iotdsl.iotDsl.Evento;
import org.xtext.example.iotdsl.iotDsl.IotDslPackage;
import org.xtext.example.iotdsl.iotDsl.Transacao;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transacao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.impl.TransacaoImpl#getEvento <em>Evento</em>}</li>
 *   <li>{@link org.xtext.example.iotdsl.iotDsl.impl.TransacaoImpl#getEstado <em>Estado</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TransacaoImpl extends MinimalEObjectImpl.Container implements Transacao
{
  /**
   * The cached value of the '{@link #getEvento() <em>Evento</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvento()
   * @generated
   * @ordered
   */
  protected Evento evento;

  /**
   * The cached value of the '{@link #getEstado() <em>Estado</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEstado()
   * @generated
   * @ordered
   */
  protected Estado estado;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransacaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IotDslPackage.Literals.TRANSACAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Evento getEvento()
  {
    if (evento != null && evento.eIsProxy())
    {
      InternalEObject oldEvento = (InternalEObject)evento;
      evento = (Evento)eResolveProxy(oldEvento);
      if (evento != oldEvento)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, IotDslPackage.TRANSACAO__EVENTO, oldEvento, evento));
      }
    }
    return evento;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Evento basicGetEvento()
  {
    return evento;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEvento(Evento newEvento)
  {
    Evento oldEvento = evento;
    evento = newEvento;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotDslPackage.TRANSACAO__EVENTO, oldEvento, evento));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Estado getEstado()
  {
    if (estado != null && estado.eIsProxy())
    {
      InternalEObject oldEstado = (InternalEObject)estado;
      estado = (Estado)eResolveProxy(oldEstado);
      if (estado != oldEstado)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, IotDslPackage.TRANSACAO__ESTADO, oldEstado, estado));
      }
    }
    return estado;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Estado basicGetEstado()
  {
    return estado;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEstado(Estado newEstado)
  {
    Estado oldEstado = estado;
    estado = newEstado;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotDslPackage.TRANSACAO__ESTADO, oldEstado, estado));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IotDslPackage.TRANSACAO__EVENTO:
        if (resolve) return getEvento();
        return basicGetEvento();
      case IotDslPackage.TRANSACAO__ESTADO:
        if (resolve) return getEstado();
        return basicGetEstado();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IotDslPackage.TRANSACAO__EVENTO:
        setEvento((Evento)newValue);
        return;
      case IotDslPackage.TRANSACAO__ESTADO:
        setEstado((Estado)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IotDslPackage.TRANSACAO__EVENTO:
        setEvento((Evento)null);
        return;
      case IotDslPackage.TRANSACAO__ESTADO:
        setEstado((Estado)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IotDslPackage.TRANSACAO__EVENTO:
        return evento != null;
      case IotDslPackage.TRANSACAO__ESTADO:
        return estado != null;
    }
    return super.eIsSet(featureID);
  }

} //TransacaoImpl
